# Generated by Django 4.0.2 on 2022-02-27 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('front_image', models.ImageField(upload_to='photos/')),
                ('url', models.URLField()),
                ('reward', models.IntegerField(blank=True, default=0)),
                ('race', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('hair_color', models.CharField(blank=True, max_length=50)),
                ('eye_color', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aliases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wanted_api.person')),
            ],
        ),
    ]
