# Generated by Django 4.0.2 on 2022-03-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='height',
        ),
        migrations.RemoveField(
            model_name='person',
            name='weight',
        ),
        migrations.AddField(
            model_name='person',
            name='age_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='age_min',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='caution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='height_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='height_min',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='weight_max',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='weight_min',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
