# Generated by Django 4.0.2 on 2022-03-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanted_api', '0003_alter_person_age_max_alter_person_age_min_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aliases',
            new_name='Alias',
        ),
    ]
