# Generated by Django 4.0.2 on 2022-03-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted_api', '0004_rename_aliases_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='front_image',
            field=models.ImageField(upload_to='./photos/'),
        ),
    ]
