# Generated by Django 4.0.2 on 2022-03-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted_api', '0005_alter_person_front_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='reward',
            field=models.TextField(blank=True, null=True),
        ),
    ]
