# Generated by Django 4.0.2 on 2022-03-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted_api', '0006_alter_person_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
